### ISSUE TITLE
Greencity- Lab test sequencing and ordering -(CRGC33)

### ISSUE THREAD

**Issue by kteamwork** [Kteamworks/KGreencity_Base1#1]
The tests under packages and profiles should be sequenced and ordered as per the document shared by Greencity hospital.

Changes taking place in: Database
Mode of changes: From front end manually

**Comment by gnauhwar** [comment]
Done the sequencing and ordering of the lab test as per request. There are 2 tests for which I need some more information.

**Comment by gnauhwar** [comment]
Resolved the issue by adding requested Procedure orders and updating existing procedure orders and lab test with their codes updated as well.
Only lab test prices are to be added. The information is NOT available with us.
