### ISSUE TITLE
Greencity - Main Report Based on Shamala's Format (CRGC21)

### ISSUE THREAD

**Issue by kteamwork** [Kteamworks/KGreencity_Base1#10]
**Requirement:** Main report as per Dr. Shamla's requirements and/or feedback
Assigned to: Chandani
Date of assigned: 3 Mar 2017

**Comment by Kteamworks** [comment]
Done. Resolved

**Comment by Kteamworks** [comment]
New Enhancements required at the bill level. 
Assigned to :  Pavithra and Geetika
