### ISSUE TITLE
Add lab test name and range in the database

### ISSUE THREAD

**Issue by Kteamworks** [Kteamworks/KGreencity_Base1#123]
Add lab test name and range in the database as given by Doctor from Greencity.

**Comment by gnauhwar** [comment]
Added and updated the lab test list as given in word document. Also, the list is not complete in terms of values or range value of around 68 tests.

**Comment by gnauhwar** [comment]
Sequence of the lab tests under its profile has been updated.

**Comment by Kteamworks** [comment]
Ranges are still missing and waiting for the same
