### ISSUE TITLE
GST- tax recalculation

### ISSUE THREAD

**Issue by Kteamworks** [Kteamworks/KGreencity_Base1#124]
As per discussion with Akhil for GST, he has explained that the tax which was 5.50%, it is 12% now. i.e. CGST (6%) & SGCT (6%)   and tax which was 14.5%, now it is 18%. i.e. CGST (9%) & SGCT (9%).
Change : Before           Now
               5.50%             12%   
               14.50%           18%
In medicine master of Greencity database

**Comment by gnauhwar** [comment]
Updated the table medicine master but there are other tax slabs like 13.50, 4,5,5.51,12.50,14.
