### ISSUE TITLE
 payment testing for ip and op patient

### ISSUE THREAD

**Issue by vinuhithi** [Kteamworks/KGreencity_Base1#131]
Testing  payment screen by creating visit for both IP and OP patients :   

scenario1:  In payment sheet for op patient their should be a doctor name and also within the braces saying consultation.
scenario2: In payment sheet for Ip patient their should be a doctor name and also their designation within the braces after discharge.
 Both the scenarios are tested and found working well in greencity demo version.

**Comment by Abilash03** [comment]
Resolved
