### ISSUE TITLE
Lab list to be added/update/deleted in the system

### ISSUE THREAD

**Issue by Kteamworks** [Kteamworks/KGreencity_Base1#136]
The list of all the lab test/packages are provided by Dr. Shyamala (counting to 205) with their respective price.

**Comment by gnauhwar** [comment]
The lab reference range values are missing in the system as they were not provided by the client. All the values are to be updated in the Laboratory Module.

**Comment by gnauhwar** [comment]
Abhilash Please provide the value if possible from Greencity.

**Comment by Kteamworks** [comment]
The updated lab list is shown to Greencity Staff by Abhilash. And this issue has been resolved. There was one more request to add some tests. That has been done. Now this issue is resolved.
