### ISSUE TITLE
Medicines without manufacturer should be removed

### ISSUE THREAD

**Issue by Kteamworks** [Kteamworks/KGreencity_Base1#140]
The medicine entry in the medicine_master table where the manufacturer names are unknown should be removed as they will be entered from the front end by the Hospital team.

Replicate the same thing in greencity_test

**Comment by gnauhwar** [comment]
Updated and also truncated data for drugs related tables like product_warehouse, drugs, drug_templates, drug_inventory, drug_sales, (codes and prices are updated for the medicine entries).

The same situation is replicated in Greencity_Test database for testing purpose.

Removed the rows in medicine master table where the name of the manufacturer is missing.
