### ISSUE TITLE
Lab data to be reentered with new data set and sequencing

### ISSUE THREAD

**Issue by Kteamworks** [Kteamworks/KGreencity_Base1#191]
Lab data to be reentered with new data set and sequencing with entry to code tables as well.
(6 apr 2018) and updates given for certain query on the same date.

**Comment by gnauhwar** [comment]
As there are entries for older patients with lab test. The older data needs to be saved with a flag and this flag field has been created as active and another column as active since.

PHP coding for queries need to be updated.
