### ISSUE TITLE
Greencity - In Financial Summary, Total amount collected,Payment by Patient, Expenditure, Discount, Doctor Charges, Due amount, pending Insurance amount

### ISSUE THREAD

**Issue by kteamwork** [Kteamworks/KGreencity_Base1#25]
Requirement: In financial summary, total amount collected, payment by patient, expenditure, discount, doctor charges, due amount, pending insurance amount need to be added
Date of assignment: 21 Mar 2017

**Comment by Kteamworks** [comment]
Insurance part and discount are remaining

**Comment by PavithraSrinivas** [comment]
Insurance Report in HIS and Due Amount calculation through bill amount-Paid Amount
