### ISSUE TITLE
Greencity - Remove Encounter, APPT-ENC,Super Bill, Eligibility, Eligibility Response, Chart Activity, chart out, Services, Syndromic  surveillance from visit

### ISSUE THREAD

**Issue by kteamwork** [Kteamworks/KGreencity_Base1#27]
Requirement: Remove encounter, APPT-ENC, super bill, eligibility, eligibility response, chart activity, chart out, Services, Syndromic  surveillance from visit
Date of assignment: 21 Mar 2017

**Comment by Kteamworks** [comment]
Done by Sada
