### ISSUE TITLE
The amount payable by any patient is set to '1' by default in the system which needs to be reset to '0' as this 1rupee gets added to the revenue hence needs to be reset to 0 as default.

### ISSUE THREAD

**Issue by PavithraSrinivas** [Kteamworks/KGreencity_Base1#58]
The amount payable by any patient is set to '1' by default in the system which needs to be reset to '0' as this 1rupee gets added to the revenue hence needs to be reset to 0 as default.

**Comment by sada059** [comment]
Resolved as price is not to be considered in finance sheet

**Comment by PavithraSrinivas** [comment]
Sada its a bill amount not the price and its included in finance sheet

**Comment by sada059** [comment]
Ok.. so what is the resolution for this?  As you said not including this in
finance will solve this? Let me know if we can close this.

**Comment by PavithraSrinivas** [comment]
Ya need to change finance reports
