### ISSUE TITLE
Remove doctors name

### ISSUE THREAD

**Issue by Kteamworks** [Kteamworks/KGreencity_Base1#77]
Remove  following Doctors name:
       a.       Dr. Shanthini
       b.       Dr. Afsha
       c.       Dr. Deepa
       d.       Dr.  Sundaramma
       e.       Dr. Tanisha
       f.       Dr. Shabana

**Comment by gnauhwar** [comment]
Completed changed user name who were wrongly mentioned as Dr. in the Users table and removed those 6 entries from codes tables as those are not doctors.
Also, removed one user who had two entries in Users table(Deepa). Kept the older one in users table.
Shanthini was not mentioned as Dr. in any of the tables.

Completed

**Comment by gnauhwar** [comment]
Added new role Lab role in the system for Shanthini.
