### ISSUE TITLE
In lab screen, provide different color for Patients having due amount

### ISSUE THREAD

**Issue by Abilash03** [Kteamworks/KGreencity_Base1#97]
In the current screen, we are displaying all patients with same color. Need to provide different color (red) for patient names who have dues.

**Comment by Abilash03** [comment]
Done

**Comment by vinuhithi** [comment]
Testing completed.
Scenarios tested are given in the attached file. All scenarios tested on Green city  test url and found to be working.
[scenario.txt](https://github.com/Kteamworks/KGreencity_Base1/files/1037901/scenario.txt)
